### PR TITLE
Delete unused file

### PR DESCRIPTION
**Pull request by raquo**
I am pretty sure this file is unused because it duplicates the code in sparkfun_serlcd.py, AND it has a syntax errors on lines 63 and 66.

### CODE REVIEW

**Review by fourstix — COMMENTED** [review]
Uh, no.  This is the concrete implementation of the parent class for I2C.  The issue is the way mitago re-factored the code.  Deleting this file is the wrong way to go, and will only make things go from bad to worse.

I plan to redo this code soon to re-write these classes altogether.

**Comment by fourstix** [comment]
Thank you.  I agree this code needs to be cleaned up so that there is one file.  But I'm not comfortable with just deleting one file without validating and refactoring the code into a single file.  So I'm going to close this pull request, and use an issue to track refactoring the code.  

I need to do more work to make sure the code should support I2C, SPI and Serial child instances of the parent class as it did when it used the Abstract Base Class.

**Comment by raquo** [comment]
Ok, sorry for misunderstanding, I assumed it was committed accidentally.

**Comment by fourstix** [comment]
No problem.  It's a mess. 

I have created the b_refactor branch with the last known good version, and then I will roll the code forward from that.  It looks like you're right, the SerLCD_I2C class needs to go.  It's easier to delete that and modify the original code.

My original SD card with the Circuit Python code is corrupt, so I don't have a raspberry pi set up to test.  But I'll recreate the test setup from scratch after I get the code working again.

**Pull request closed without merging**
